[versions]
kotlin = "1.7.10"
kotlinx = "1.5.0"
cucumber = "7.11.2"
vertxImpl = "4.4.1"
vertx = "1.4.0"
kmongo = "4.9.0"

[libraries]
kotlinx-ser-core = {module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref="kotlinx"}
kotlinx-ser-json = {module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="kotlinx"}
cucumber-java = {module = "io.cucumber:cucumber-java",  version.ref="cucumber"}
cucumber-junit = {module = "io.cucumber:cucumber-junit",  version.ref="cucumber"}
cucumber-java8 = {module = "io.cucumber:cucumber-java8",  version.ref="cucumber"}
junit-vintage = "org.junit.vintage:junit-vintage-engine:5.9.2"
vertx-web = {module = "io.vertx:vertx-web", version.ref="vertxImpl"}
vertx-web-client = {module = "io.vertx:vertx-web-client", version.ref="vertxImpl"}
netty = "io.netty:netty-all:4.1.90.Final" # remove vertx warning on MacOS

#probably not all dependencies are needed (to check)
kmongo-base = {module = "org.litote.kmongo:kmongo", version.ref="kmongo"}
kmongo-coroutine = {module = "org.litote.kmongo:kmongo-coroutine", version.ref="kmongo"}
kmongo-async = {module = "org.litote.kmongo:kmongo-async", version.ref="kmongo"}
kmongo-reactor = {module = "org.litote.kmongo:kmongo-reactor", version.ref="kmongo"}

[bundles]
kotlinx = ["kotlinx-ser-core", "kotlinx-ser-json"]
cucumber = ["cucumber-java", "cucumber-junit", "cucumber-java8"]
vertx-server = ["vertx-web", "netty"]
vertx-full = ["vertx-web", "vertx-web-client", "netty"] # server + client
kmongo = ["kmongo-base", "kmongo-coroutine", "kmongo-async", "kmongo-reactor"]


[plugins]
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
vertx = {id = "io.vertx.vertx-plugin", version.ref = "vertx"}
johnrengelman-shadow = "com.github.johnrengelman.shadow:7.0.0" #allow execute shadowJar task
cucumber-runner = "se.thinkcode.cucumber-runner:0.0.11"  #add gradle task for running cucumber